import type { Metadata } from "next";
import { Roboto as RobotoFont } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/providers/providers";




const roboto = RobotoFont(
  {
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"]
    // Add your Roboto font options here if needed
  }
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
export default RootLayout